# Fichier: docker-compose.infra.yml
version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: llmbasedos_redis
    command: redis-server --requirepass ${REDIS_PASSWORD} # Utilise la variable du .env
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - llmbasedos-net

  ollama:
    image: ollama/ollama:latest
    container_name: llmbasedos_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - llmbasedos-net

  memobase:
    image: ghcr.io/memodb-io/memobase:latest
    container_name: llmbasedos_memobase
    networks:
      - llmbasedos-net
    ports:
      - "8019:8019"
    volumes:
      - ./memobase_config/config.yaml:/app/api/config.yaml:ro # <-- LE TIREt (-) ÉTAIT MANQUANT ICI
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@memobase_db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/1
      - MEMOBASE_LLM_API_KEY=${MEMOBASE_PROJECT_TOKEN}
      - MEMOBASE_LLM_BASE_URL=http://paas:8000/v1
      - MEMOBASE_ENABLE_EVENT_EMBEDDING=false
    depends_on:
      - redis
      - memobase_db
    restart: unless-stopped

  memobase_db:
    image: pgvector/pgvector:pg15
    container_name: llmbasedos_memobase_db
    networks:
      - llmbasedos-net
    ports:
      - "${POSTGRES_PORT}:5432" # Port externe configurable
    env_file: # <-- AJOUTEZ CECI
      - .env  # <-- AJOUTEZ CECI
    environment:
      # Ces variables sont maintenant lues depuis le .env
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - llmbasedos_memobase_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  ollama_models:
  llmbasedos_memobase_data:

networks:
  llmbasedos-net:
    name: llmbasedos-net # <-- AJOUTEZ CETTE LIGNE
    driver: bridge