services:
  llmbasedos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llmbasedos_paas
    networks:
      - llmbasedos-net
    privileged: true
    tty: true
    volumes:
      - ./llmbasedos_src:/opt/app/llmbasedos_src:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/llmbasedos:ro
      - ./data:/data:rw
      - ./supervisord.conf:/etc/supervisor/conf.d/llmbasedos.conf:ro
    environment:
      - PLAYWRIGHT_URL=http://playwright-mcp:5678
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - playwright-mcp

  playwright-mcp:
    # On construit notre propre image fiable
    build:
      context: ./playwright-mcp 
    image: playwright-mcp:latest
    container_name: llmbasedos_playwright
    networks:
      - llmbasedos-net
    restart: unless-stopped
    ports:
      - "5678:5678"

networks:
  llmbasedos-net:
    driver: bridge