# MemoBase Configuration
llm_api_key: "${MEMOBASE_LLM_API_KEY}"
llm_base_url: "${MEMOBASE_LLM_BASE_URL}"
llm_model: "gemini-1.5-pro-latest"
best_llm_model: "gemini-1.5-pro-latest"
thinking_llm_model: "gemini-1.5-pro-latest"

# Database
database_url: "${DATABASE_URL}"
redis_url: "${REDIS_URL}"

# Features
enable_event_embedding: false
llm_sanity_check: false

# Server
host: "0.0.0.0"
port: 8019